version: '2'

services:

  varnish:
    image: eeacms/varnish
    depends_on:
      - web
    links:
      - web
    ports:
      - "127.0.0.1:8000:6081"
    environment:
      BACKENDS: "web"
      BACKENDS_PORT: "80"
      BACKENDS_PROBE_ENABLED: "false"
    restart: always

  web:
    build: .
    image: acspri/qamd-web
    volumes:
      - ./:/var/www/html/
    restart: always

